# Go 
# Build your Go project. 
trigger: 
   - master
  
pool:
   vmImage: 'ubuntu-latest'
  
steps: 
  - task: GoTool@0
    inputs:
      version: '1.14.4'
  - task: Go@0
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)/server'
  - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)/server'
  - task: CopyFiles@2
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
       artifactName: drop
  - task: NodeTool@0
    inputs:
      versionSpec: '12.6.0'
      displayName: 'Install Node.js'
  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'npm install and build'
  - task: CopyFiles@2
    inputs:
      Contents: 'dist/**' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
  - task: PublishBuildArtifacts@1
    inputs: 
      pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
      ArtifactName: 'www' # output artifact named www
   
